### PR TITLE
Added getClubCampaignById

### PR DESCRIPTION
**Pull request by Sigeth**
getClubCampaignById allows to access to a campaign using its club ID and its campaign ID.

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
This PR introduce the new geyClubCampaignById.
It allows to access to a campaign by its club ID and its campaign ID.

* **What is the current behavior?** (You can also link to an open issue here)
//

* **What is the new behavior (if this is a feature change)?**
Explained in the introduction

* **Other information**:
I tried to implement it but I'm not sure if it works exactly like I did.
If you could check, it's working but my declarations may be false.

Here are the changes :
- live-services.js : from line 88 to line 111
- live-services.d.ts : from line 40 to line 51 and from line 286 to line 299

Thanks for reading it and please let me know if I need to fix things !
(if you want an example of the JSON that is returning, just ask me, but I think it's the same as campaigns from getClubCampaigns)

### CODE REVIEW

**Comment by breeku** [comment]
Hey,

thanks for the pr!

there's some funky stuff here though.

---

```
Here are the changes :

    live-services.js : from line 88 to line 111
    live-services.d.ts : from line 40 to line 51 and from line 286 to line 299

```
this is not reflected in the pr, since there is a diff of 
```diff 
+571
-656
```

atleast some of this seems to be due to not using [prettier](https://prettier.io), look into installing that extension to your editor.

why is ```live-services.spec.ts``` overwritten with types and function definitions?

in ```live-services.ts``` there's some new weird imports and all functions are moved from export const to exports? also there is some source mapping at the end of file

---

the getClubCampaignById function by itself look's like it should work though, there's just some weird stuff happening otherwise.

are you sure you are making changes to the source and not the built files? there should not be .d.ts in the source

**Comment by Sigeth** [comment]
Ok so, just to ask :
Why do I need to change in order to make a new function ?
Do I need to create a new interface or smth ?
I think I'll wait your comment, then close this PR and open another one with less weird things I think

**Comment by Sigeth** [comment]
I'm closing it, I'll make another PR today I think or in the next days

**Comment by breeku** [comment]
Hey, sorry it's taking time to answer, busy times.

In nutshell, you need to clone the repository, and then edit the files in ./src/ directory. Look at the other functions for direction how they are constructed.

**Pull request closed without merging**
